import { createHash } from "node:crypto";
import { mkdir, readFile, readdir, writeFile } from "node:fs/promises";
import { createRequire } from "node:module";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

import { build } from "esbuild";

// This file belongs in tools/. Only installed, lockfile-controlled packages are read.
const root = fileURLToPath(new URL("../", import.meta.url));
const vendorDirectory = join(root, "site", "assets", "vendor");
const require = createRequire(import.meta.url);
const packageDirectories = new Map();

async function packageForFile(file) {
  const visited = [];
  let directory = dirname(file);
  while (true) {
    if (packageDirectories.has(directory)) {
      const found = packageDirectories.get(directory);
      for (const visitedDirectory of visited) packageDirectories.set(visitedDirectory, found);
      return found;
    }
    visited.push(directory);
    try {
      const metadata = JSON.parse(await readFile(join(directory, "package.json"), "utf8"));
      if (metadata.name && metadata.version) {
        const found = { directory, ...metadata };
        for (const visitedDirectory of visited) packageDirectories.set(visitedDirectory, found);
        return found;
      }
    } catch (error) {
      if (error.code !== "ENOENT") throw error;
    }
    const parent = dirname(directory);
    if (parent === directory) throw new Error(`No package metadata found for ${file}`);
    directory = parent;
  }
}

async function licenseNotices(pkg) {
  const files = (await readdir(pkg.directory, { withFileTypes: true }))
    .filter((entry) => entry.isFile() && /^(?:licen[cs]e|copying|notice|copyright)(?:[._-].*)?$/i.test(entry.name))
    .map((entry) => entry.name)
    .sort();
  if (!files.length) throw new Error(`No upstream license notice found for ${pkg.name}@${pkg.version}`);
  const sections = await Promise.all(files.map(async (file) =>
    `--- ${pkg.name}@${pkg.version}: ${file} ---\n${await readFile(join(pkg.directory, file), "utf8")}`
  ));
  return sections.join("\n\n");
}

const d3Entry = require.resolve("d3");
const d3Package = await packageForFile(d3Entry);
const hlsPackage = await packageForFile(require.resolve("hls.js"));
const d3Bundle = await build({
  absWorkingDir: root,
  entryPoints: [d3Entry],
  bundle: true,
  platform: "browser",
  format: "iife",
  globalName: "d3",
  target: "es2017",
  minify: true,
  legalComments: "inline",
  metafile: true,
  write: false,
  outfile: join(vendorDirectory, "d3.min.js"),
  banner: { js: `// D3 ${d3Package.version}; bundled from locked npm packages. See LICENSES.txt.` },
  footer: { js: `d3.version = ${JSON.stringify(d3Package.version)};` },
});

const runtimePackages = new Map();
for (const input of Object.keys(d3Bundle.metafile.inputs).sort()) {
  const pkg = await packageForFile(resolve(root, input));
  runtimePackages.set(pkg.directory, pkg);
}
runtimePackages.set(hlsPackage.directory, hlsPackage);
const packages = [...runtimePackages.values()].sort((first, second) => {
  const firstKey = `${first.name}@${first.version}`;
  const secondKey = `${second.name}@${second.version}`;
  return firstKey < secondKey ? -1 : firstKey > secondKey ? 1 : 0;
});
const notices = await Promise.all(packages.map(licenseNotices));

// Retain any companion notices that the prebuilt HLS distribution supplies.
const hlsDist = join(hlsPackage.directory, "dist");
for (const entry of (await readdir(hlsDist, { withFileTypes: true })).sort((first, second) =>
  first.name < second.name ? -1 : first.name > second.name ? 1 : 0
)) {
  if (entry.isFile() && /^hls\.min\.js\.(?:LICENSE|LEGAL|NOTICE)\.txt$/i.test(entry.name)) {
    notices.push(`--- ${hlsPackage.name}@${hlsPackage.version}: dist/${entry.name} ---\n${await readFile(join(hlsDist, entry.name), "utf8")}`);
  }
}

const assets = {
  d3: { version: d3Package.version, file: "d3.min.js", bytes: d3Bundle.outputFiles[0].contents },
  hls: { version: hlsPackage.version, file: "hls.min.js", bytes: await readFile(join(hlsDist, "hls.min.js")) },
};
const metadata = {};
await mkdir(vendorDirectory, { recursive: true });
for (const [name, asset] of Object.entries(assets)) {
  const sha256 = createHash("sha256").update(asset.bytes).digest("hex");
  metadata[name] = { version: asset.version, file: asset.file, sha256 };
  await writeFile(join(vendorDirectory, asset.file), asset.bytes);
}
await writeFile(join(vendorDirectory, "vendor-assets.js"),
  `// Generated by tools/build_vendor_assets.mjs.\nglobalThis.PARLIAMENT_STREAMS_VENDOR = ${JSON.stringify(metadata, null, 2)};\n`
);
await writeFile(join(vendorDirectory, "LICENSES.txt"),
  `Runtime package notices for the generated D3 and HLS.js assets.\nHLS.js also uses the full Apache License 2.0; see APACHE-2.0.txt in this directory.\n\n${notices.join("\n\n")}\n`
);
console.log(`Generated local D3 ${d3Package.version} and HLS.js ${hlsPackage.version} assets with ${packages.length} package notices.`);
